Feature: Generate After Block Exception
  In order to test that exceptions in after blocks are reported by testjour
  As a testjour developer
  I want to cause the After block to raise an exception
  
  Scenario: Raise After block exception
    Given I am a naughty step
  
  
  

  
